

#index_list:
 # path: /index
  #controller: App\Controller\ArticleController::index

#index_new:
 # path: /index/new
  #controller: App\Controller\ArticleController::index2


# article_list:
#  path: /
 # controller: App\Controller\ArticleController::list



#new_article:
# path: /new
# controller: App\Controller\ArticleController::new

